# Generated by Django 4.1.5 on 2023-01-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Figura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rotulo", models.CharField(max_length=50)),
                ("legenda", models.CharField(max_length=50)),
                ("imagem", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Artigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_do_periodico", models.CharField(max_length=100)),
                ("titulo_do_artigo", models.CharField(max_length=100)),
                ("volume", models.IntegerField()),
                ("numero", models.IntegerField()),
                ("ano_de_publicacao", models.IntegerField()),
                ("autores", models.ManyToManyField(to="core.autores")),
            ],
        ),
    ]
