# Generated by Django 4.1.5 on 2023-01-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Autores",
            new_name="Autor",
        ),
    ]
