# Generated by Django 4.1.5 on 2023-02-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_figura_imagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artigo",
            name="autores",
        ),
        migrations.AddField(
            model_name="artigo",
            name="autores",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artigos",
                to="core.autor",
            ),
        ),
    ]
